services:
  web:
    # Override command for development
    command: python manage.py runserver 0.0.0.0:8000
    # Mount the code for development (selective mounting)
    volumes:
      # Mount only specific directories to avoid reinstalling requirements
      - ./apps:/app/apps
      - ./ecommerce_api:/app/ecommerce_api
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      # Mount individual files that might change frequently
      - ./manage.py:/app/manage.py
      - ./.env:/app/.env
      - ./.env.docker:/app/.env.docker
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
    # Use development environment
    env_file:
      - .env.docker
    # Enable debugging
    environment:
      - DEBUG=True

  # Add pgadmin for database management in development
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
