services:
  web:
    # Use gunicorn for production
    command: gunicorn ecommerce_api.wsgi:application --bind 0.0.0.0:8000
    # Don't mount code in production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    # Use production environment
    env_file:
      - .env.prod
    # Disable debugging
    environment:
      - DEBUG=False
    # Restart policy
    restart: always

  # Add nginx for serving static files and as a reverse proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume:
